### ISSUE TITLE
手机端的部署

### ISSUE THREAD

**Issue by yuqian2019** [deepconsc/SplitSR#1]
请问您是用什么工具将模型部署在手机端，以及具体的部署步骤会release吗？

**Comment by deepconsc** [comment]
I should firstly clarify, that I'm not the author of the SplitSR [paper](https://arxiv.org/abs/2101.07996), neither is this official implementation. 
Regarding the deployment on mobile phones - easiest approach would be PyTorch -> ONNX -> TFLite. There are many issues covered in online discussions in case you meet some issue during the process. 
Also, PyTorch had some major updates recently, including [PyTorch Mobile](https://pytorch.org/mobile/home/), but it's relatively new and there's no guarantee you'll find all the answers online yet.
